// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAop2l65v9mTPHQ93z6WF_1jspuZAidVHk',
    appId: '1:258479380466:web:43d7f0da2d604786e97d6b',
    messagingSenderId: '258479380466',
    projectId: 'social-media-app-4ec7a',
    authDomain: 'social-media-app-4ec7a.firebaseapp.com',
    storageBucket: 'social-media-app-4ec7a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdlqj0fe4PctIt23shxAB5SDHTii8Vi_Y',
    appId: '1:258479380466:android:17fb18b3157d033de97d6b',
    messagingSenderId: '258479380466',
    projectId: 'social-media-app-4ec7a',
    storageBucket: 'social-media-app-4ec7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4D4u3u6C9Nl1vHYWfhI6MyP4Azd0M7kI',
    appId: '1:258479380466:ios:96db9ff69d0d49fae97d6b',
    messagingSenderId: '258479380466',
    projectId: 'social-media-app-4ec7a',
    storageBucket: 'social-media-app-4ec7a.appspot.com',
    androidClientId: '258479380466-irgpk12a9b5qjkvdu0csoq64jolajlhe.apps.googleusercontent.com',
    iosClientId: '258479380466-8n26e1dmkpr7rinr6ceuuu9lb81h7v06.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4D4u3u6C9Nl1vHYWfhI6MyP4Azd0M7kI',
    appId: '1:258479380466:ios:3980abb1997f5efae97d6b',
    messagingSenderId: '258479380466',
    projectId: 'social-media-app-4ec7a',
    storageBucket: 'social-media-app-4ec7a.appspot.com',
    androidClientId: '258479380466-irgpk12a9b5qjkvdu0csoq64jolajlhe.apps.googleusercontent.com',
    iosClientId: '258479380466-u85qonfqtlm8nsj7t06e3ad86g4nor2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
